Config:
  world: world
  prefix: '&2&lGunGame'
  
Spawn:
  x: 1284
  y: 243
  z: -347
  
Pos1:
  x: 50
  y: 50
  z: 50
  
Pos2:
  x: 50
  y: 50
  z: 50
  
MySQL:
  host: localhost
  port: 3306
  database: gungame
  username: root
  password: lukas321